#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "The pycrypt installer must be run as root" 1>&2
   exit 1
fi

cp pycrypt /usr/bin/pycrypt

echo "Installed!"
echo "To use, run pycrypt [Options] from the command line"
