#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "The installer must be run as root" 1>&2
   exit 1
fi
echo '#!/usr/bin/python' > pycrypt
cat pycrypt.py >> pycrypt
mv pycrypt /usr/bin/pycrypt
chmod +x /usr/bin/pycrypt

echo '#!/usr/bin/python' > pykeygen
cat pykeygen.py >> pykeygen
mv pykeygen /usr/bin/pykeygen
chmod +x /usr/bin/pykeygen
echo "Installed!"
echo "To use, run pycrypt [Options] and pykeygen [Options] from the command line"
